"use client";

import { useState } from "react";
import { ArrowRight, ArrowUpRight, BrainCircuit, CalendarDays, CheckCircle2, Code2, Compass, Menu, MessageSquareMore, MoveUpRight, Newspaper, Plus, Quote, Radar, Rocket, Sparkles, UsersRound, X, type LucideIcon } from "lucide-react";

const features: [LucideIcon, string, string, string][] = [[Code2, "01", "Desafios práticos", "Construa projetos reais e transforme estudo em portfólio."], [MessageSquareMore, "02", "Feed inteligente", "Troque ideias, dúvidas e descobertas com quem está evoluindo."], [CalendarDays, "03", "Eventos ao vivo", "Encontre encontros, workshops e oportunidades para participar."], [Newspaper, "04", "Radar tech", "Conteúdo selecionado para você acompanhar o que importa."]];
const faqs = [["O que é a Baldin?", "A Baldin é uma comunidade para pessoas que querem aprender, criar e crescer na tecnologia em conjunto."], ["Preciso já trabalhar com tecnologia?", "Não. A comunidade foi pensada para diferentes momentos da jornada, do primeiro projeto à transição de carreira."], ["Como posso participar?", "Crie seu perfil, explore os conteúdos e escolha uma conversa, desafio ou evento para começar."]];
const navItems = [["Recursos", "#recursos"], ["Mapa de evolução", "#mapa"], ["Comunidade", "#comunidade"], ["FAQ", "#faq"]];

export default function BaldinPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="baldin-shell">
    <header className="baldin-header"><nav className="baldin-container nav-content" aria-label="Navegação principal">
      <a href="#inicio" className="brand" aria-label="Baldin, início"><span className="brand-mark"><Rocket size={19} /></span><span>Baldin</span></a>
      <div className="desktop-nav">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div>
      <div className="nav-actions"><a href="#jornada" className="button button-small hide-mobile">Começar agora <ArrowUpRight size={16} /></a><button className="icon-button mobile-only" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} aria-expanded={menuOpen}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div>
    </nav>{menuOpen && <div className="mobile-nav">{navItems.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</div>}</header>

    <main>
      <section id="inicio" className="hero-section"><div className="grid-atmosphere" /><div className="baldin-container hero-grid">
        <div className="hero-copy reveal"><p className="eyebrow">A próxima fase da sua jornada</p><h1>Sua vida <span>tech</span> em um só lugar.</h1><p className="hero-description">Aprenda no seu ritmo, encontre sua comunidade e transforme curiosidade em movimento. A Baldin reúne tudo que você precisa para evoluir na tecnologia.</p><div className="hero-actions"><a href="#jornada" className="button">Entrar na comunidade <ArrowRight size={17} /></a><a href="#mapa" className="button button-ghost">Explorar a Baldin <Compass size={17} /></a></div><div className="hero-proof"><span className="signal-dot" /><span>Uma comunidade em movimento</span><div className="avatar-stack"><i /><i /><i /><b>+</b></div></div></div>
        <div className="profile-window reveal-delay"><div className="window-bar"><span><i /><i /><i /></span><code>baldin.profile</code></div><div className="profile-image"><div className="profile-overlay" /><div className="profile-card"><p className="eyebrow">Seu próximo capítulo</p><strong>Aprender. Criar. Conectar.</strong><div className="progress"><span /></div><small>72% de uma jornada que está só começando</small></div></div></div>
      </div></section>
      <div className="ticker"><div className="ticker-track"><span>APRENDIZADO CONTÍNUO</span><Sparkles size={15} /><span>COMUNIDADE REAL</span><Sparkles size={15} /><span className="cyan-text">PROJETOS QUE MOVEM</span><Sparkles size={15} /><span>FUTURO EM CONSTRUÇÃO</span><Sparkles size={15} /></div></div>

      <section id="recursos" className="baldin-section"><div className="baldin-container"><div className="section-heading"><div><p className="eyebrow">Tudo em um só lugar</p><h2>Ferramentas para <span>destravar</span> seu potencial.</h2></div><p>Uma experiência criada para tornar a evolução mais prática, conectada e possível.</p></div><div className="feature-grid">{features.map(([Icon, index, title, text]) => <article className="feature-card" key={title}><span className="feature-icon"><Icon size={21} /></span><small>{index}</small><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section id="mapa" className="baldin-section section-bottom"><div className="baldin-container evolution"><div className="evolution-main"><p className="eyebrow">Seu mapa de evolução</p><h2>Você não precisa descobrir o caminho <span>sozinho.</span></h2><p className="muted-copy">Acompanhe possibilidades, reconheça seus avanços e encontre novas direções com uma comunidade que entende a jornada.</p><div className="stats-grid"><div><BrainCircuit size={20} /><strong>∞</strong><small>possibilidades</small></div><div><UsersRound size={20} /><strong>+1k</strong><small>pessoas conectadas</small></div><div><Radar size={20} /><strong>24/7</strong><small>conteúdo em movimento</small></div></div></div><aside className="pulse-panel"><p className="eyebrow">Pulso da comunidade</p><h3>O que está acontecendo agora</h3>{[["IA aplicada", "Conversas e projetos em alta", "EM ALTA"], ["Portfolio review", "Encontro ao vivo nesta semana", "AO VIVO"], ["Trilha de dados", "Nova jornada disponível", "NOVO"]].map(([title, text, tag]) => <div className="pulse-item" key={title}><div><strong>{title}</strong><small>{text}</small></div><span>{tag}</span></div>)}</aside></div></section>
      <section id="comunidade" className="baldin-section section-bottom"><div className="baldin-container community"><div className="community-visual"><div className="visual-label"><p className="eyebrow">Gente que faz acontecer</p><strong>Ideias ganham força quando encontram outras ideias.</strong></div></div><div className="community-copy"><p className="eyebrow">Mais que conteúdo</p><h2>Um lugar para <span>pertencer</span> enquanto você cresce.</h2><p className="large-copy">Aqui, cada pergunta pode abrir uma porta. Cada projeto pode aproximar pessoas. E cada pequeno avanço merece ser reconhecido.</p>{["Aprenda com experiências reais, não só com teoria.", "Construa conexões que continuam além da tela.", "Encontre espaço para testar, errar e tentar de novo."].map(point => <p className="check-line" key={point}><CheckCircle2 size={18} />{point}</p>)}</div></div></section>
      <section id="jornada" className="baldin-section section-bottom"><div className="baldin-container"><div className="section-heading narrow"><div><p className="eyebrow">Comece de onde estiver</p><h2>Uma jornada com espaço para <span>você.</span></h2></div><p>Não existe um jeito único de evoluir. Existe o próximo passo que faz sentido para você.</p></div><div className="steps-grid">{[["01", "Chegue com curiosidade", "Explore temas, pessoas e possibilidades sem precisar ter todas as respostas."], ["02", "Coloque a mão na massa", "Escolha um desafio, compartilhe uma ideia e transforme intenção em prática."], ["03", "Evolua em comunidade", "Celebre avanços, peça ajuda e ajude outras pessoas a avançarem também."]].map(([number, title, text]) => <article key={number}><small>{number}</small><h3>{title}</h3><p>{text}</p></article>)}</div><div className="quotes-grid"><blockquote><Quote size={22} /><p>“A tecnologia ficou menos solitária quando encontrei pessoas com o mesmo brilho nos olhos.”</p><footer>Marina, produto e dados</footer></blockquote><blockquote><Quote size={22} /><p>“A Baldin me deu clareza para transformar o que eu estudava em algo que eu queria construir.”</p><footer>Caio, desenvolvimento</footer></blockquote></div></div></section>
      <section id="faq" className="baldin-section faq-section"><div className="baldin-container faq-container"><p className="eyebrow">Ainda ficou alguma dúvida?</p><h2>Perguntas <span>frequentes.</span></h2><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={19} /></summary><p>{answer}</p></details>)}</div></div></section>
      <section className="baldin-section"><div className="baldin-container cta-banner"><p className="eyebrow">Seu próximo passo começa agora</p><h2>O futuro não precisa esperar.</h2><p>Traga sua curiosidade. A gente encontra o caminho junto.</p><a href="#inicio" className="button button-light">Quero fazer parte <MoveUpRight size={17} /></a></div></section>
    </main>
    <footer className="baldin-footer"><div className="baldin-container footer-content"><div className="brand"><span className="brand-mark"><Rocket size={19} /></span><span>Baldin</span></div><p>Uma comunidade para quem quer construir o próximo capítulo da tecnologia.</p><div className="footer-links">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div><small>© 2026 Baldin. Feito para quem está em movimento.</small></div></footer>
  </div>;
}